### ISSUE TITLE
canvas

### ISSUE THREAD

**Issue by RenXiaoF** [Mr-Eve/ngx-signature-pad#1]
This method "activePad()"  runs incorrectly.

I am a small white, do not know the description is right

**Comment by RenXiaoF** [comment]
node_modules\@eve-sama\ngx-signature-pad\lib\ngx-signature-pad.component.d.ts
 private get activePad();
运行时：
 An accessor cannot be declared in an ambient context.
 private get activePad();

**Comment by Eve-Sama** [comment]
无法复现. 请问你的TS依赖版本是多少呢? TS版本3.7及以上是比较推荐的.

**Comment by RenXiaoF** [comment]
这个附件是个简单的测试项目。
ng serve 运行就会出现那个错误
http://localhost:4201/canvas&nbsp; 这个路由


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Eve-Sama/ngx-signature-pad"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 晚上11:47
收件人:&nbsp;"Eve-Sama/ngx-signature-pad"<ngx-signature-pad@noreply.github.com&gt;;
抄送:&nbsp;"任小飞"<1273024925@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Eve-Sama/ngx-signature-pad] canvas (#1)





 
无法复现. 请问你的TS依赖版本是多少呢? TS版本3.7及以上是比较推荐的.

**Comment by Eve-Sama** [comment]
在你的项目中, 我看到package中写了TS依赖是
     
     "typescript": "~3.4.3"

ng版本为8, 建议升级为10. 因为报错的那句语法要求TS版本为3.7以上. ng8到10应该还是比较好升的. 
另外, 不要在issue区发布你的源码, 这样你的源码就全部泄露了, 如果是商业项目这样不太好. 建议删除关于源码的那句issue
