### ISSUE TITLE
not launch

### ISSUE THREAD

**Issue by Paul75** [Mr-Eve/ngx-signature-pad#7]
Hello,

I got this error when  launching ...

![image (1)](https://user-images.githubusercontent.com/457062/201641993-a6025b8e-8a65-4bb1-804c-e1d975bdd0b0.png)

Thanks

**Comment by Eve-Sama** [comment]
what's your ng version? Does it occur in new ng project?

**Comment by Paul75** [comment]
![IMG_20221116_110748_edit_258399363500](https://user-images.githubusercontent.com/457062/202152044-e225708b-2fca-41ba-93c6-9c847feccdcb.jpg)

**Comment by Eve-Sama** [comment]
Try use it in new v14 project. If it still occur error, feedback to me.
